;; The sequence of triangle numbers is generated by adding the natural numbers. So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

;; Let us list the factors of the first seven triangle numbers:

;;      1: 1
;;      3: 1,3
;;      6: 1,2,3,6
;;     10: 1,2,5,10
;;     15: 1,3,5,15
;;     21: 1,3,7,21
;;     28: 1,2,4,7,14,28

;; We can see that 28 is the first triangle number to have over five divisors.

;; What is the value of the first triangle number to have over five
;; hundred divisors?


;; logic: always has 2 (itself and 1) and they come in pairs (e.g 2/3
;; for 6) so only have to go up to the square root of the number

(defn divisors
  [n]
  (loop [i (Math/floor (Math/sqrt n)) divs 2]
    (cond
     (= 1 i) divs
     :else (if (zero? (mod n i))
             (recur (dec i) (+ divs 2))
             (recur (dec i) divs)))))

(loop [n 1 total 0]
  (if (< 500 (divisors (+ total n)))
    (+ n total)
    (recur (inc n) (+ n total))))



