;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;Find the sum of all the even-valued terms in the sequence which do not exceed four million.

(defn next-fib 
  [fib-seq] 
  (reduce + (take-last 2 fib-seq)))

(reduce +
        (filter even?
                (loop [fib-seq [0 1]] 
                  (let [next (next-fib fib-seq)]
                    (if (< 4000000 next)
                      fib-seq 
                      (recur (conj fib-seq next)))))))

